# Generated by Django 3.2.11 on 2022-04-07 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField()),
                ('book', models.IntegerField()),
                ('progress', models.TextField()),
            ],
            options={
                'db_table': 'bookprogress',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='bookprogress',
            index=models.Index(fields=['book'], name='bookprogress_idx'),
        ),
    ]
