version: "3.9"
services:
  web:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "/e/Documents/CalibreLibrary:/CWA/UserLibrary"
      - "/home/massiveatoms/deploytest/CalibreWAN/Persistent:/CWA/Persistent"
    env_file:
      - ".env"