version: "3.9"
services:
  web:
    build:
      context: ../
      dockerfile: ./deploy/Dockerfile
    ports:
      - "8000:80"
    volumes:
      - "/path/to/CalibreLibrary:/CWA/UserLibrary"
      - "/path/to/Persistent:/CWA/Persistent"
    env_file:
      - ".env"
